name: Deploy

on:
  release:
    types: [published]

jobs:
  build-wheel-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: RalfG/python-wheels-manylinux-build@v0.3.4-manylinux2014_x86_64
        with:
          python-versions: 'cp310-cp310 cp311-cp311 cp312-cp312'
          build-requirements: 'mypy'
      - name: Upload wheel
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
  build-wheel-matrix:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        os: [macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: setup xcode version
        if: startsWith(matrix.os, 'macos')
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14'
      - name: python
        uses: actions/setup-python@v4
        with:
            python-version: ${{ matrix.python-version }}
      - name: Build
        run: |
          pip wheel . --no-deps -w dist
      - name: Upload wheel
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: [build-wheel-linux, build-wheel-matrix]
    steps:
      - name: checkout source code
        uses: actions/checkout@v4
      - name: Load artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - name: Remove linux_x86_64 wheels
        run: rm dist/*-linux_x86_64.whl
      - name: Publish distribution package to PyPI
        #if: env.branch == 'master'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.pypi_password }}
