name: run all tests

on: [push, pull_request]

jobs:
  test:
    strategy:
        fail-fast: false
        matrix:
            python-version: ["3.10", "3.11", "3.12"]
            os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    name: run tests
    steps:
      - name: setup xcode version
        if: startsWith(matrix.os, 'macos')
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13'
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: python
        uses: actions/setup-python@v4
        with:
            python-version: ${{ matrix.python-version }}
      - name: install requirements
        run: |
          pip install wheel
          pip install mypy
          python -m mypy --version
      - name: output mypy version
        run: python -m mypy --version
      - name: install package
        run: pip install . -v
      - name: test
        run: |
          python tests.py
